name: Tests
on: [push, pull_request]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.0,8.1,8.2]
        composer-flags: [null, --prefer-lowest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - run: composer update ${{ matrix.composer-flags }} --no-interaction --no-progress --prefer-dist --ansi
      - run: npm install
      - run: ./vendor/bin/phpunit --color=always
