name: Tests
on: [push, pull_request]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4, 8.0,8.1,8.2,8.3]
        composer-flags: [null, --prefer-lowest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
            node-version: 21.0.0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - run: composer update ${{ matrix.composer-flags }} --no-interaction --no-progress --prefer-dist --ansi
      - run: npm install
      - name: Build assets
        run: npm run build
      - run: ./vendor/bin/phpunit --color=always
